name: ChatPlugin
main: eu.cloudnetservice.chatsystem.ChatPlugin
version: ${chat.version}

api-version: 1.13
author: CloudNetService

depend: [CloudNetAPI]

description: CloudNet Chat System for the Central server
website: https://cloudnetservice.eu/

